server:
  port: 8080

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://auth.bezzone.me/realms/Final-TP}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: orders-service-route
              uri: ${ORDER_API_URL:https://ticket-app-sd2-253296968289.us-central1.run.app}
              predicates:
                - Path=/api/orders/**, /api/events/**, /api/admin/**, /internal/**